Add support for zone type forward
cloudfoundry-community/bind9-boshrelease pull request #5
Opened 2017-07-07 19:27 UTC by ntdt

Allow to add config for zone type forward.
My use case is to forward request to consul DNS in case of Vault in HA with consul backend, e.g.

>  forward:
>     zones:
>         service.consul: |
>             type forward;
>             forward only;
>             forwarders { 10.0.0.1; 10.0.0.2; 10.0.0.3; };

will generate

> zone "service.consul" in {
>   type forward;
>   forward only;
>   forwarders { 10.0.0.1; 10.0.0.2; 10.0.0.3; };
> };

Add  an entry DNS to `myvault.example.com IN CNAME active.vault.service.consul` will return the IP of active Vault node.

2017-07-09 15:24 UTC, jhunt requested changes
Can we handle the zone configuration for forwarding _explicitly_ in the template, rather than just pass through the literal from the configuration?  I know we did this for zone definitions, but that was because handling every possible ask of a DNS server in YAML/spec was deemed too much work for the effort.  However, configuring forwarders would be nicer if I could say:

```
properties:
  bind9:
    forward:
      zones:
        zone1:
          forwards:
            - 10.0.0.2
            - 10.0.0.3
```

like the spec file currently implies.

2017-07-09 15:24 UTC, jhunt commented on jobs/master/spec
> +    description: "Forward zones in forward only mode,e.g. {name: zone1, forwarders: [1.1.1.1, 1.1.1.2]}"
The spec description seems to indicate that I don't have to generate literal BIND9 configurations for the forwarding zones, but the implementation seems to differ markedly.

2017-07-10 15:42 UTC, ntdt commented
Thank @jhunt for comments, I've pushed a new commit to match the required spec:
From properties
```
bind9:
  forward:
    zones:
      - name: service.consul
        forwarders:
          - 10.00.0.1
          - 10.0.0.2
          - 10.0.0.3
```
generates this config with new templates
```
zone "service.consul" in {
  type forward;
  forward only;
  forwarders {
          10.220.225.1;
          10.220.225.2;
          10.220.225.3;
      };
};
```

2017-07-10 18:18 UTC, jhunt approved these changes

2017-07-10 18:18 UTC, merged

2017-07-10 18:18 UTC, jhunt commented
Thanks!